version: '3.5'

services:

  consul:
    image: consul:1.6.3
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - consul-net

  weather-forecast-service:
    restart: on-failure
    build:
      context: weather-forecast-service
      dockerfile: docker/DockerFile
    ports:
      - "7000-7005:7000"
    networks:
      - consul-net

  what-to-do-service:
    restart: on-failure
    build:
      context: what-to-do-service
      dockerfile: docker/DockerFile
    ports:
      - "7010:7000"
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge
