server:
  port: 7000

spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
    org.springframework.cloud:
      consul: DEBUG

